---
# tasks file for cockpit
- name: gather facts
  gather_facts:

- name: Gather package facts
  package_facts:
    manager: auto

- name: Gather service facts
  service_facts:

- name: Install AWS CLI client & Apache Tools
  dnf:
    name:
      - awscli
      - httpd-tools
      - python3-passlib

- name: Set AWS Access Key ID (ec2-user)
  become: false
  shell: aws configure set aws_access_key_id {{ aws_access_key_id }}
  when: aws_access_key_id | length > 0 
  
- name: Set AWS Secret Access Key (ec2-user)
  become: false
  shell: aws configure set aws_secret_access_key {{ aws_secret_access_key }} 
  when: aws_secret_access_key | length > 0

- name: Set AWS Default Region (ec2-user)
  become: false
  shell: aws configure set default.region {{ default_region }}
  when: default_region | length > 0
  
- name: Set AWS Default Output (ec2-user)
  become: false
  shell: aws configure set default.output {{ default_output }}
  when: default_output | length > 0

- name: Set AWS Access Key ID
  shell: aws configure set aws_access_key_id {{ aws_access_key_id }}
  when: aws_access_key_id | length > 0 
  
- name: Set AWS Secret Access Key
  shell: aws configure set aws_secret_access_key {{ aws_secret_access_key }} 
  when: aws_secret_access_key | length > 0

- name: Set AWS Default Region
  shell: aws configure set default.region {{ default_region }}
  when: default_region | length > 0
  
- name: Set AWS Default Output
  shell: aws configure set default.output {{ default_output }}
  when: default_output | length > 0

# - name: Create rosa directory if it does not exist
#   file:
#     path: "{{ oc_dir }}/rosa"
#     state: directory
#     mode: '0755'

- name: "Install ROSA client"
  shell: |
    set -euo pipefail

    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz | \
    tar -xvzf - -C {{ oc_dir }}/ rosa && chmod 755 {{ oc_dir }}/rosa && ln -s {{ oc_dir }}/rosa
  ignore_errors: true

- name: ROSA login
  shell: rosa login --token "{{ rosa_api_token }}"
  ignore_errors: true
...
