---
# tasks file for cockpit
- name: gather facts
  gather_facts:

- name: Gather package facts
  package_facts:
    manager: auto

- name: Gather service facts
  service_facts:

- name: Install AWS CLI client 
  dnf:
    name:
      - awscli

- name: Set AWS Access Key ID
  shell: aws configure set aws_access_key_id {{ aws_access_key_id }} 
  
- name: Set AWS Secret Access Key
  shell: aws configure set aws_secret_access_key {{ aws_secret_access_key }} 

- name: Set AWS Default Region
  shell: aws configure set default.region {{ default_region }}
  
- name: Set AWS Default Output
  shell: aws configure set default.output {{ default_output }}

- name: "Install ROSA client"
  shell: |
    set -euo pipefail

    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz | \
    tar -xvzf - -C {{ oc_dir }}/rosa && chmod 755 {{ oc_dir }}/rosa && ln -s {{ oc_dir }}/rosa

...
