---
# tasks file for cockpit
- name: gather facts
  gather_facts:

- name: Gather package facts
  package_facts:
    manager: auto

- name: Gather service facts
  service_facts:

- name: Import the Microsoft repository key
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Create local azure-cli repository information
  shell: |
    echo -e "[azure-cli]
    name=Azure CLI
    baseurl=https://packages.microsoft.com/yumrepos/azure-cli
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/azure-cli.repo

- name: Install Azure CLI client 
  dnf:
    name:
      - azure-cli

...
