---
- name: Wait for ROSA cluster creation to complete
  shell: rosa list clusters
  register: rosa_cluster_state
  retries: 32
  delay: 150
  until: rosa_cluster_state.stdout.find("ready") != -1

- name: Create cluster-admin account
  shell: rosa create admin --cluster="rosa-{{ instance_tag }}"
  register: rosa_cluster_admin

# - debug:
#     var: "{{ rosa_cluster_admin.stdout_lines[3] }}"

- set_fact:
    rosa_cluster_admin_login: "{{ rosa_cluster_admin.stdout_lines[4] }}"

- name: Login to ROSA cluster
  shell: "{{ rosa_cluster_admin_login }}"
  register: login_result
  retries: 20
  delay: 30
  until: login_result.rc == 0

- name: OC pull htpasswd-secret to local machine
  shell: oc get secret htpasswd-secret -ojsonpath={.data.htpasswd} -n openshift-config | base64 --decode > users.htpasswd

# - name: Create User Account
#   htpasswd:
#     path: users.htpasswd
#     name: "{{ item }}"
#     password: openshift
#   with_sequence: "start=1 end={{ student_total }} format={{ student_prefix }}%02d"

- name: OC update file with user login data
  shell: htpasswd -bB users.htpasswd {{ item }} openshift
  with_sequence: "start=1 end={{ student_total }} format={{ student_prefix }}%02d"

- name: OC push htpasswd-secret to cluster
  shell: oc create secret generic htpasswd-secret --from-file=htpasswd=users.htpasswd --dry-run=client -o yaml -n openshift-config | oc replace -f -

- name: Import and apply mongodb-persistent template 
  shell: oc create -n openshift -f https://raw.githubusercontent.com/RH-ANZ-Workshops/anzworkshop/main/mongodb-persistent-template-4.9.json

- name: Retrieve cluster URL
  shell: rosa describe cluster -c "rosa-{{ instance_tag }}" | grep Console
  register: cluster_url

# - name: ROSA login
#   shell: rosa create account-roles --mode auto --yes

# - name: Create rosa directory if it does not exist
#   file:
#     path: "{{ oc_dir }}/rosa"
#     state: directory
#     mode: '0755'

# - name: "Install ROSA client"
#   shell: |
#     set -euo pipefail

#     curl -L https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz | \
#     tar -xvzf - -C {{ oc_dir }}/ rosa && chmod 755 {{ oc_dir }}/rosa && ln -s {{ oc_dir }}/rosa
#   ignore_errors: true
...
