---
- name: Wait for ROSA cluster creation to complete
  shell: rosa list clusters
  register: rosa_cluster_state
  until: rosa_cluster_state.stdout.find("ready") != -1
  retries: 18
  delay: 300

- name: Create cluster-admin account
  shell: rosa create admin --cluster="rosa-{{ instance_tag }}"
  register: rosa_cluster_admin

# - debug:
#     var: "{{ rosa_cluster_admin.stdout_lines[3] }}"

- set_fact:
    rosa_cluster_admin_login: "{{ rosa_cluster_admin.stdout_lines[0] }}"

- name: Login to ROSA cluster
  shell: "{{ rosa_cluster_admin_login }}"

- name: OC pull htpasswd-secret to local machine
  shell: oc get secret htpasswd-secret -ojsonpath={.data.htpasswd} -n openshift-config | base64 --decode > users.htpasswd

- name: OC update file with user login data
  shell: htpasswd -bB users.htpasswd user1 openshift

- name: OC push htpasswd-secret to cluster
  shell: oc create secret generic htpasswd-secret --from-file=htpasswd=users.htpasswd --dry-run=client -o yaml -n openshift-config | oc replace -f -

# - name: ROSA login
#   shell: rosa create account-roles --mode auto --yes

# - name: Create rosa directory if it does not exist
#   file:
#     path: "{{ oc_dir }}/rosa"
#     state: directory
#     mode: '0755'

# - name: "Install ROSA client"
#   shell: |
#     set -euo pipefail

#     curl -L https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz | \
#     tar -xvzf - -C {{ oc_dir }}/ rosa && chmod 755 {{ oc_dir }}/rosa && ln -s {{ oc_dir }}/rosa
#   ignore_errors: true
...
